"""wmlib — helpers for world_model.py. You do not edit this file. The world-model contract is in
world_model.py; this is the toolbox it imports.

  clone(state)          deep-copy a state (transition mutates a copy)
  segment(grid)         compact 4-connected components: bbox + exact row-run shape
  segment_summary(grid) text summary of segment(...) without cell lists
  composite(parts, h, w[, background])  the inverse: parts -> grid
  diff_text(prev, nxt)          compact lossless cell-delta description (rectangles, not per-cell tuples)
  current_frame_key()           latest observed (level, turn)
  current_grid()                the latest observed grid (numpy HxW int16)
  current_state(model)          model's believed CURRENT state (simulates forward over observed actions)
  frames() / transitions()      current-attempt grids / (prev,next,action) triples, as numpy
  attempts()                    prior reset-attempt roots; pass a root to frames()/transitions()
  death_events()                fatal actions preserved outside normal transitions
  terminal_events()             observed winning-terminal frame per solved level (render ground-truth)
  animation_index()             compact metadata for saved transient animation events
  animation_grids(event_or_dir) targeted loader for saved animation grids
  verify(model)                 simulate model over observed transitions; simulation_accuracy + diagnostics
  verify_outcome(model)         falsify outcome() against level-complete and GAME_OVER evidence
  plan_bfs / plan_astar / plan_subgoals(model, start[, target, ...])  search to level_complete
  validate_plan(model, start, plan[, target, ...])  replay-check a candidate plan
  UNKNOWN = -1                  render(state) may use this for genuinely unclaimed cells
Functions starting with _ are internal.
"""

from __future__ import annotations

import glob
import heapq
import json
import os
from collections import deque

import numpy as np

OBSERVATION_VARIANT_LIMIT = 5
UNKNOWN = -1
GAME_OVER_ACTION_SCAN_LIMIT = 4096
GAME_OVER_ACTION_EXAMPLE_LIMIT = 8
GAME_OVER_CLICK_REGION_LIMIT = 8
OUTCOME_ONGOING = "ongoing"
OUTCOME_LEVEL_COMPLETE = "level_complete"
OUTCOME_GAME_OVER = "game_over"
VALID_OUTCOMES = {OUTCOME_ONGOING, OUTCOME_LEVEL_COMPLETE, OUTCOME_GAME_OVER}


def clone(state):
    """Deep-copy a state so transition() mutates a copy (the planner holds many states at once)."""
    import copy as _copy
    return _copy.deepcopy(state)


def outcome(model, state) -> str:
    """Strictly read the model's terminal/status output.

    The prompt-visible world-model contract requires outcome(state) to return exactly one of:
    "ongoing", "level_complete", or "game_over".
    """
    if not hasattr(model, "outcome") or not callable(model.outcome):
        raise AttributeError("world_model.py must define outcome(state)")
    value = model.outcome(state)
    if value not in VALID_OUTCOMES:
        raise ValueError(
            "outcome(state) must return exactly one of "
            f"{sorted(VALID_OUTCOMES)}, got {value!r}"
        )
    return value


def is_level_complete(model, state) -> bool:
    return outcome(model, state) == OUTCOME_LEVEL_COMPLETE


def is_game_over(model, state) -> bool:
    return outcome(model, state) == OUTCOME_GAME_OVER


def composite(parts, h, w, background=0):
    """parts -> grid: lay each part's cells (in order) over a background of size h×w. The inverse of
    segment(..., include_cells=True)."""
    g = np.full((h, w), background, dtype=np.int16)
    for p in parts:
        for (r, c) in p["cells"]:
            if 0 <= r < h and 0 <= c < w:
                g[r, c] = p["color"]
    return g


def _hashable(o):
    """Stable, hashable view of an arbitrary value — handles dataclass/object/dict/list/tuple/numpy/
    sets. The planner uses this to dedup search nodes, generically over whatever fields your State has."""
    if isinstance(o, np.ndarray):
        return ("ndarray", str(o.dtype), tuple(o.shape), o.tobytes(order="C"))
    if isinstance(o, np.generic):
        return o.item()
    if hasattr(o, "__dict__") and not isinstance(o, type):
        return ("obj", tuple(sorted((k, _hashable(v)) for k, v in vars(o).items())))
    if isinstance(o, dict):
        return tuple(sorted((k, _hashable(v)) for k, v in o.items()))
    if isinstance(o, (list, tuple)):
        return tuple(_hashable(v) for v in o)
    if isinstance(o, set):
        return tuple(sorted(_hashable(v) for v in o))
    try:
        hash(o); return o
    except TypeError:
        return repr(o)


def segment(grid=None, background=None, include_background=False, include_cells=False):
    """4-connected components. Compact by default: no cells, bbox plus exact row-run shape.
    Non-rectangles use relative row-runs, e.g. shape="0:0-2;1:0" for an L-shape."""
    if grid is None:
        grid = current_grid()
    if grid is None:
        return []
    g = np.asarray(grid, dtype=np.int16)
    if g.ndim != 2:
        raise ValueError(f"expected a 2-D grid, got shape {g.shape}")
    h, w = g.shape
    if background is None:
        vals, cnts = np.unique(g, return_counts=True)
        background = int(vals[cnts.argmax()])
    else:
        background = int(background)
    parts = []
    labels = np.full((h, w), -1, dtype=np.int32)
    seen = np.zeros((h, w), bool)
    if not include_background:
        seen[g == background] = True
    for i in range(h):
        for j in range(w):
            if seen[i, j]:
                continue
            pid = len(parts)
            color = int(g[i, j]); cells = []; dq = deque([(i, j)]); seen[i, j] = True
            while dq:
                r, c = dq.popleft(); cells.append((int(r), int(c))); labels[r, c] = pid
                for dr, dc in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nr, nc = r + dr, c + dc
                    if 0 <= nr < h and 0 <= nc < w and not seen[nr, nc] and g[nr, nc] == color:
                        seen[nr, nc] = True; dq.append((nr, nc))
            cells = sorted(cells)
            rs = [r for r, _ in cells]; cs = [c for _, c in cells]
            r0, r1, c0, c1 = min(rs), max(rs), min(cs), max(cs)
            rows = {}
            for r, c in cells:
                rows.setdefault(r - r0, []).append(c - c0)
            filled = len(cells) == (r1 - r0 + 1) * (c1 - c0 + 1)
            rec = {
                "id": int(pid), "color": color, "size": int(len(cells)),
                "bbox": (int(r0), int(c0), int(r1), int(c1)),
                "centroid": (round(float(sum(rs) / len(cells)), 2),
                             round(float(sum(cs) / len(cells)), 2)),
                "shape": "rect" if filled else ";".join(f"{r}:{_runs(cols)}" for r, cols in sorted(rows.items())),
                "adjacent": [],
            }
            if include_cells:
                rec["cells"] = cells
            parts.append(rec)
    adj = [set() for _ in parts]
    for r in range(h):
        for c in range(w):
            pid = int(labels[r, c])
            if pid < 0:
                continue
            if r + 1 < h:
                qid = int(labels[r + 1, c])
                if qid >= 0 and qid != pid:
                    adj[pid].add(qid); adj[qid].add(pid)
            if c + 1 < w:
                qid = int(labels[r, c + 1])
                if qid >= 0 and qid != pid:
                    adj[pid].add(qid); adj[qid].add(pid)
    for pid, neighbors in enumerate(adj):
        parts[pid]["adjacent"] = sorted(int(x) for x in neighbors)
    return parts


def segment_summary(grid=None, background=None, include_background=False, max_components=80):
    """Human-readable segment(...) summary; no cell lists."""
    if grid is None:
        grid = current_grid()
    if grid is None:
        return "no current grid"
    g = np.asarray(grid, dtype=np.int16)
    if background is None:
        vals, cnts = np.unique(g, return_counts=True)
        background = int(vals[cnts.argmax()])
    else:
        background = int(background)
    parts = segment(g, background=background, include_background=include_background, include_cells=False)
    shown = parts[:max_components]
    lines = [
        f"grid={g.shape[0]}x{g.shape[1]} background={background} "
        f"components={len(parts)} include_background={bool(include_background)}"
    ]
    for p in shown:
        r0, c0, r1, c1 = p["bbox"]
        lines.append(
            f"#{p['id']} color={p['color']} size={p['size']} "
            f"bbox=({r0},{c0})-({r1},{c1}) centroid={p['centroid']} "
            f"shape={p['shape']} adjacent={p['adjacent']}"
        )
    if len(parts) > len(shown):
        lines.append(f"... {len(parts) - len(shown)} more components omitted")
    return "\n".join(lines)


def _runs(cols):
    """Collapse a sorted col list into comma-separated ranges: [36,37,38,40] -> '36-38,40'."""
    cs = sorted(cols); out = []; s = p = cs[0]
    for c in cs[1:]:
        if c == p + 1:
            p = c
        else:
            out.append((s, p)); s = p = c
    out.append((s, p))
    return ",".join(f"{a}-{b}" if a != b else f"{a}" for a, b in out)


def diff_text(prev, nxt) -> str:
    """Compact, lossless cell-delta description for two grids. Cells with the same (old->new) color
    transition are grouped, contiguous columns collapse to ranges, contiguous rows that share an
    identical col-spec collapse to row-ranges. A block recolor that would otherwise be 38 one-cell
    lines becomes ONE line ('9->8 rows 44-49, cols 36-41'). The exact cells are recoverable from
    the ranges. Use this anywhere you need a token-cheap diff (kickoff messages, run reports)."""
    from collections import defaultdict
    a, b = np.asarray(prev, dtype=np.int16), np.asarray(nxt, dtype=np.int16)
    d = [(r, c, int(a[r, c]), int(b[r, c])) for r, c in np.argwhere(a != b)]
    if not d:
        return "no cells changed"
    rs = [r for r, _, _, _ in d]; cs = [c for _, c, _, _ in d]
    bbox = f"rows {min(rs)}-{max(rs)}, cols {min(cs)}-{max(cs)}"
    by_trans: dict = defaultdict(lambda: defaultdict(list))   # (old,new) -> row -> [cols]
    for r, c, o, n in d:
        by_trans[(o, n)][r].append(c)
    lines = []
    for (o, n), rows in sorted(by_trans.items()):
        rowspec = [(r, _runs(rows[r])) for r in sorted(rows)]
        i = 0
        while i < len(rowspec):
            r0, spec = rowspec[i]; j = i
            while j + 1 < len(rowspec) and rowspec[j + 1][1] == spec and rowspec[j + 1][0] == rowspec[j][0] + 1:
                j += 1
            rng = f"rows {r0}-{rowspec[j][0]}" if j > i else f"row {r0}"
            lines.append(f"  {o}->{n}  {rng}, cols {spec}")
            i = j + 1
    return f"{len(d)} cells changed; region [{bbox}]\n" + "\n".join(lines)


# ---- observed data (already parsed to numpy; never hand-parse hex) ----
def _read(path):
    rows = []
    for line in open(path).read().splitlines():
        s = line.strip()
        if not s or s.startswith("x:"):
            continue
        if ":" in s:
            s = s.split(":", 1)[1]
        toks = s.replace("|", " ").split()
        if toks and all(len(t) == 1 for t in toks):
            rows.append([int(t, 16) for t in toks])
        elif len(toks) == 1 and len(toks[0]) > 1:
            rows.append([int(ch, 16) for ch in toks[0]])
    return np.array(rows, dtype=np.int16)


def frames(root="."):
    """{(level, turn): grid} for every observed frame, all levels."""
    out = {}
    for f in sorted(glob.glob(os.path.join(root, "level_*", "turn_*.txt"))):
        lvl = int(os.path.basename(os.path.dirname(f)).split("_")[1])
        t = int(os.path.basename(f).split("_")[1].split(".")[0])
        out[(lvl, t)] = _read(f)
    return out


def transitions(root="."):
    """Observed transitions: [{level, turn, prev, next, action, row, col}, ...] across all levels.
    (row,col) is the ACTION6 click cell, else None."""
    fr = frames(root); out = []
    for (lvl, t), g in sorted(fr.items()):
        prev = fr.get((lvl, t - 1))
        if prev is None:
            continue
        mp = os.path.join(root, f"level_{lvl}", f"turn_{t:03d}.json")
        m = json.load(open(mp)) if os.path.exists(mp) else {}
        row = m.get("row", m.get("y")); col = m.get("col", m.get("x"))
        out.append({"level": lvl, "turn": t, "prev": prev, "next": g,
                    "action": m.get("action"), "row": row, "col": col})
    return out


def attempts(root="."):
    """Prior reset attempts, oldest first.

    Each record has ``level``, ``attempt``, ``reason``, ``n_frames``, and ``root``. The root is an
    immutable observation tree with the same layout as the live workspace, so reuse the normal
    accessors: ``wmlib.frames(root=a["root"])``, ``wmlib.transitions(root=a["root"])``, and
    ``wmlib.animation_index(root=a["root"])``. Pass the same root to ``animation_grids`` when
    loading an archived event.
    Default frames()/transitions() intentionally remain current-attempt only so simulation and
    planning never stitch evidence across RESET boundaries.
    """
    out = []
    for f in glob.glob(os.path.join(root, "attempts", "level_*_attempt_*", "attempt.json")):
        try:
            event = json.load(open(f))
            event["root"] = os.path.dirname(f)
            out.append(event)
        except Exception:  # noqa: BLE001
            pass
    return sorted(out, key=lambda e: (int(e.get("level", -1)), int(e.get("attempt", -1))))


def current_frame_key(root="."):
    """The latest observed frame key as (level, turn), respecting the harness marker when present."""
    fr = frames(root)
    marker = os.path.join(root, ".current_frame.json")
    if os.path.exists(marker):
        try:
            m = json.load(open(marker))
            key = (int(m["level"]), int(m["turn"]))
            if key in fr:
                return key
        except Exception:
            pass
    return max(fr) if fr else None


def current_grid(root="."):
    """The latest observed grid (numpy int16 HxW)."""
    fr = frames(root)
    key = current_frame_key(root)
    return fr[key] if key in fr else None


def current_state(model, root="."):
    """The model's believed state at NOW: init_state on this level's first frame, then transition()
    threaded over every observed action — carries hidden state up to now (a fresh init_state on the
    current grid would lose it). Falls back to init_state(current_grid()) if the model can't simulate."""
    fr = frames(root)
    if not fr:
        return None
    cur_lvl = max(lvl for (lvl, _) in fr)
    seq = [t for t in transitions(root) if t["level"] == cur_lvl]
    cur = fr[max(fr)]
    if not seq:
        return model.init_state(cur, cur_lvl)
    try:
        state = model.init_state(seq[0]["prev"], cur_lvl)
        for t in seq:
            state = model.transition(state, _act(t))
        return state
    except Exception:  # noqa: BLE001 — never crash a planner-prep helper
        return model.init_state(cur, cur_lvl)


# ---- internals ----
def _act(t):
    """The action dict {action, row, col} passed to transition()."""
    return {"action": t["action"], "row": t["row"], "col": t["col"]}


def _variant_items(raw, limit=OBSERVATION_VARIANT_LIMIT):
    """Normalize observation_variants(state) to at most `limit` grid-like objects.

    The intended contract is list[grid]. Be forgiving for a common mistake: returning a single HxW
    grid instead of [grid]. Do not be forgiving enough to create an unbounded verifier escape hatch.
    """
    if raw is None:
        return [], False
    if isinstance(raw, np.ndarray):
        if raw.ndim == 2:
            return [raw], False
        if raw.ndim == 3:
            return [raw[i] for i in range(min(raw.shape[0], limit))], raw.shape[0] > limit
        return [], False
    if isinstance(raw, (list, tuple)):
        arr = np.asarray(raw)
        if arr.ndim == 2:
            return [raw], False
        if arr.ndim == 3:
            return list(raw[:limit]), len(raw) > limit
        return list(raw[:limit]), len(raw) > limit
    out = []
    truncated = False
    try:
        it = iter(raw)
        for i, item in enumerate(it):
            if i >= limit:
                truncated = True
                break
            out.append(item)
    except TypeError:
        return [], False
    return out, truncated


def _render_candidates(model, state):
    """Canonical render plus bounded optional observation variants.

    render(state) is the Moore-machine output and stays mandatory. observation_variants(state), when
    present, is verifier-only: a bounded set of alternate observed grids accepted for display
    quantization (HUD bars, rounded counters), not alternative dynamics or planner states.
    """
    variant_errors = []
    try:
        primary = np.asarray(model.render(state), dtype=np.int16)
    except Exception as e:  # noqa: BLE001
        return {"primary": None, "candidates": [], "variant_count": 0,
                "variant_truncated": False, "variant_errors": [],
                "render_error": f"{type(e).__name__}: {e}"}

    candidates = [("render", primary)]
    raw_fn = getattr(model, "observation_variants", None)
    truncated = False
    if callable(raw_fn):
        try:
            raw = raw_fn(state)
            items, truncated = _variant_items(raw)
            for i, item in enumerate(items):
                try:
                    candidates.append((f"observation_variants[{i}]", np.asarray(item, dtype=np.int16)))
                except Exception as e:  # noqa: BLE001
                    variant_errors.append(f"observation_variants[{i}] -> array raised {type(e).__name__}: {e}")
        except Exception as e:  # noqa: BLE001
            variant_errors.append(f"observation_variants() raised {type(e).__name__}: {e}")
    return {"primary": primary, "candidates": candidates, "variant_count": max(0, len(candidates) - 1),
            "variant_truncated": truncated, "variant_errors": variant_errors, "render_error": None}


def _cell_stats(pred, obs):
    """Cell-level diagnostics for a render candidate.

    UNKNOWN (-1) means "this cell is intentionally unclaimed by render(state)". Accepted matching
    ignores unknown cells, but strict/cell diagnostics still expose the abstention through coverage.
    """
    if pred is None or pred.shape != obs.shape:
        return {"shape_ok": False, "full_cell_ok": 0, "known_cell_ok": 0, "known_cell_n": 0,
                "unknown_cell_n": 0, "cell_n": int(obs.size), "coverage": None,
                "coverage_status": "unobserved",
                "known_cell_accuracy": None, "partial_ok": False, "strict_ok": False}
    unknown = (pred == UNKNOWN)
    known = ~unknown
    cell_n = int(obs.size)
    known_cell_n = int(np.count_nonzero(known))
    unknown_cell_n = cell_n - known_cell_n
    full_cell_ok = int(np.count_nonzero(pred == obs))
    known_cell_ok = int(np.count_nonzero((pred == obs) & known))
    coverage = known_cell_n / cell_n if cell_n else None
    known_acc = known_cell_ok / known_cell_n if known_cell_n else None
    return {"shape_ok": True,
            "full_cell_ok": full_cell_ok,
            "known_cell_ok": known_cell_ok,
            "known_cell_n": known_cell_n,
            "unknown_cell_n": unknown_cell_n,
            "cell_n": cell_n,
            "coverage": coverage,
            "coverage_status": _coverage_status(coverage),
            "known_cell_accuracy": known_acc,
            "partial_ok": known_cell_n > 0 and known_cell_ok == known_cell_n,
            "strict_ok": bool(np.array_equal(pred, obs))}


def _coverage_status(coverage):
    """Human-facing coverage bucket for UNKNOWN-aware renders.

    complete: render() claimed every cell.
    partial : render() abstained on some cells with UNKNOWN=-1.
    vacuous : render() abstained on every cell; this is not evidence of a correct model.
    """
    if coverage is None:
        return "unobserved"
    if coverage <= 0:
        return "vacuous"
    if coverage >= 0.999999:
        return "complete"
    return "partial"


def _predicts_change(pred, prev) -> bool:
    """Whether a rendered prediction claims any visible change from prev.

    UNKNOWN cells are abstentions, not claimed changes. This keeps a model that leaves newly revealed
    viewport cells unclaimed from being graded as "changed" solely because -1 differs from the prior
    observed color.
    """
    if pred is None:
        return False
    if pred.shape != prev.shape:
        return True
    known = pred != UNKNOWN
    return bool(np.any((pred != prev) & known))


def _known_mismatches(pred, obs):
    if pred is None or pred.shape != obs.shape:
        return np.empty((0, 2), dtype=np.int16)
    return np.argwhere((pred != obs) & (pred != UNKNOWN))


def _render_match(model, state, observed):
    """Return strict and variant-accepted match diagnostics for one rendered state."""
    obs = np.asarray(observed)
    info = _render_candidates(model, state)
    primary = info["primary"]
    primary_stats = _cell_stats(primary, obs)
    primary_shape_ok = bool(primary_stats["shape_ok"])
    strict_ok = bool(primary_stats["strict_ok"])
    primary_partial_ok = bool(primary_stats["partial_ok"]) if primary_shape_ok else False
    best = primary
    best_label = "render" if primary is not None else None
    best_stats = primary_stats
    best_cell_ok = primary_stats["known_cell_ok"] if primary_shape_ok else -1

    accepted_ok = bool(primary_shape_ok and primary_partial_ok)
    accepted_label = "render" if accepted_ok else None
    accepted_stats = primary_stats if accepted_ok else None
    for label, cand in info["candidates"][1:]:
        stats = _cell_stats(cand, obs)
        if not stats["shape_ok"]:
            info["variant_errors"].append(
                f"{label} shape {cand.shape} != observed {obs.shape}; variants must be full-grid render alternatives"
            )
            continue
        if primary_shape_ok and not np.array_equal(cand == UNKNOWN, primary == UNKNOWN):
            introduced = int(np.count_nonzero((cand == UNKNOWN) & (primary != UNKNOWN)))
            filled = int(np.count_nonzero((cand != UNKNOWN) & (primary == UNKNOWN)))
            info["variant_errors"].append(
                f"{label} changes the UNKNOWN mask from render() "
                f"(introduced {introduced}, filled {filled}); observation_variants() may vary only "
                "claimed display cells and must preserve render()'s UNKNOWN=-1 cells exactly"
            )
            continue
        c_ok = stats["known_cell_ok"]
        if c_ok > best_cell_ok:
            best = cand
            best_label = label
            best_stats = stats
            best_cell_ok = c_ok
        if primary_shape_ok and stats["partial_ok"]:
            accepted_ok = True
            accepted_label = label
            accepted_stats = stats
            break

    info.update({
        "primary_shape_ok": primary_shape_ok,
        "strict_ok": strict_ok,
        "accepted_ok": accepted_ok,
        "accepted_label": accepted_label,
        "accepted_by_variant": bool(accepted_ok and accepted_label != "render"),
        "accepted_by_unknown": bool(accepted_ok and accepted_stats and accepted_stats["unknown_cell_n"] > 0
                                    and not (accepted_label == "render" and strict_ok)),
        "best": best,
        "best_label": best_label,
        "primary_stats": primary_stats,
        "accepted_stats": accepted_stats,
        "best_stats": best_stats,
    })
    return info


# ---- verification: SIMULATION accuracy (the model-quality metric) ----
def verify(model, root="."):
    """Check render(init_state(grid0, level)) independently, then simulate model from s0 and score
    render(s_i) against observed grid_i — WITHOUT re-reading observed grids. By default every cell is graded: a move/
    life counter rendered to pixels is real state, so render() should reproduce it. render() may use
    UNKNOWN (-1) only for cells the model explicitly cannot claim yet (for example newly revealed
    viewport cells). UNKNOWN cells are ignored by the accepted-transition match but reported through
    coverage/known-cell diagnostics. Denominator is GRADED transitions: observed-grid changes plus
    false model-predicted changes on observed no-ops. Real no-ops where both observation and model
    stay visually unchanged are skipped. Returns:
      simulation_accuracy : float|None   fraction reproduced exactly; None if n_changing=0
                                         Uses bounded observation_variants() when supplied.
      strict_simulation_accuracy : float|None  fraction where canonical render() matched exactly
      cell_accuracy       : float|None   diagnostic per-cell agreement over grading transitions
      known_cell_accuracy : float|None   per-cell agreement over non-UNKNOWN canonical render cells
      prediction_coverage : float|None   fraction of canonical render cells that were claimed
      initial_render_ok   : bool|None    whether every level start is reproduced (variants/UNKNOWN accepted)
      initial_render_strict_accuracy : float|None  exact canonical-render level-start match rate
      n_changing, n_total : int          graded / all observed transitions  (n_changing/n_total is
                                         the fraction of the run that's actually grading material)
      n_matched           : int          graded transitions reproduced by the model
      n_observed_changed  : int          observed transitions with a visible grid change
      n_joint_noop        : int          observed no-ops also predicted as no-ops (not graded)
      n_unpredicted_noop  : int          observed no-ops where transition/render raised (not graded)
      archived_*          : int/dict     prior RESET-attempt evidence inventoried but not replay-scored
      per_level           : {level: {simulation_accuracy, strict_simulation_accuracy,
                                     cell_accuracy, n_changing, first_divergence}}
      first_divergence    : {level,turn,action,diff}|None   the first transition the model gets wrong
      errors              : [str]        init_state/transition exceptions (check first if accuracy is 0/None)
    """
    fr = frames(root)
    trans = transitions(root)
    by_level = {}
    for t in trans:
        by_level.setdefault(t["level"], []).append(t)

    errors = []
    initial_render_errors = []
    per = {}
    total_chg = total_ok = 0
    total_strict_ok = 0
    total_variant_used = 0
    total_cell_ok = total_cell_n = 0
    total_known_cell_ok = total_known_cell_n = total_unknown_cell_n = 0
    total_unknown_used = total_unknown_accepts = 0
    total_observed_changed = total_observed_noop = total_joint_noop = total_unpredicted_noop = 0
    total_false_change_on_noop = 0
    initial_n = initial_ok = initial_strict_ok = 0
    initial_cell_ok = initial_cell_n = 0
    initial_known_cell_ok = initial_known_cell_n = initial_unknown_cell_n = 0
    initial_variant_used = initial_unknown_used = 0
    variant_errors = []
    levels = sorted({lvl for lvl, _ in fr})
    for lvl in levels:
        seq = by_level.get(lvl, [])
        initial_grid = seq[0]["prev"] if seq else fr[min(k for k in fr if k[0] == lvl)]
        init_error = None
        try:
            state = model.init_state(initial_grid, lvl)
        except Exception as e:  # noqa: BLE001
            state = None
            init_error = f"init_state() raised {type(e).__name__}: {e}"
            errors.append(f"level {lvl}: {init_error}")
            initial_render_errors.append(f"level {lvl}: {init_error}")

        initial_match = None
        if state is not None:
            initial_match = _render_match(model, state, initial_grid)
            if initial_match.get("render_error"):
                init_error = f"render(init_state()) raised {initial_match['render_error']}"
                initial_render_errors.append(f"level {lvl}: {init_error}")
            for ve in initial_match.get("variant_errors") or []:
                msg = f"level {lvl} initial render: {ve}"
                if msg not in variant_errors and len(variant_errors) < 8:
                    variant_errors.append(msg)
            if initial_match.get("variant_truncated"):
                msg = (f"level {lvl} initial render: observation_variants() returned more than "
                       f"{OBSERVATION_VARIANT_LIMIT}; extras ignored")
                if msg not in variant_errors and len(variant_errors) < 8:
                    variant_errors.append(msg)

        initial_n += 1
        init_stats = (initial_match or {}).get("primary_stats") or {}
        init_accepted = bool(initial_match and initial_match.get("accepted_ok") and not init_error)
        init_strict = bool(initial_match and initial_match.get("strict_ok") and not init_error)
        initial_ok += int(init_accepted)
        initial_strict_ok += int(init_strict)
        initial_cell_ok += int(init_stats.get("full_cell_ok", 0))
        initial_cell_n += int(init_stats.get("cell_n", initial_grid.size))
        initial_known_cell_ok += int(init_stats.get("known_cell_ok", 0))
        initial_known_cell_n += int(init_stats.get("known_cell_n", 0))
        initial_unknown_cell_n += int(init_stats.get("unknown_cell_n", 0))
        initial_variant_used += int(bool(initial_match and initial_match.get("accepted_by_variant")))
        initial_unknown_used += int(bool(init_stats.get("unknown_cell_n", 0)))
        init_first = None
        if not init_accepted:
            pred = (initial_match or {}).get("primary")
            if init_error:
                init_first = init_error
            elif pred is None:
                init_first = "render(init_state()) produced no prediction"
            elif pred.shape != initial_grid.shape:
                init_first = f"render shape {pred.shape} != observed {initial_grid.shape}"
            else:
                best = (initial_match or {}).get("best")
                compare = best if best is not None and best.shape == initial_grid.shape else pred
                mismatch = _known_mismatches(compare, initial_grid)
                loc = tuple(int(v) for v in mismatch[0]) if len(mismatch) else "(no claimed cell)"
                init_first = f"{len(mismatch)} claimed cells differ; first at {loc}"
        n_chg = n_ok = 0
        n_observed_changed = n_observed_noop = n_joint_noop = n_unpredicted_noop = 0
        n_false_change_on_noop = 0
        n_strict_ok = n_variant_used = 0
        cell_ok = cell_n = 0
        known_cell_ok = known_cell_n = unknown_cell_n = 0
        n_unknown_used = n_unknown_accepts = 0
        lvl_first = None
        for t in seq:
            prev, nxt = t["prev"], t["next"]
            obs_changed = not np.array_equal(prev, nxt)
            n_observed_changed += int(obs_changed)
            n_observed_noop += int(not obs_changed)
            # advance the simulation (thread our own predicted state forward, even on no-op observations
            # — a "no-op" might still tick a hidden counter the next action depends on)
            pred = None
            match = None
            if state is not None:
                try:
                    state = model.transition(state, _act(t))
                    match = _render_match(model, state, nxt)
                    pred = match["primary"]
                    for ve in match.get("variant_errors") or []:
                        msg = f"level {lvl} turn {t['turn']}: {ve}"
                        if msg not in variant_errors and len(variant_errors) < 8:
                            variant_errors.append(msg)
                    if match.get("variant_truncated"):
                        msg = (f"level {lvl} turn {t['turn']}: observation_variants() returned more than "
                               f"{OBSERVATION_VARIANT_LIMIT}; extras ignored")
                        if msg not in variant_errors and len(variant_errors) < 8:
                            variant_errors.append(msg)
                    if match.get("render_error"):
                        raise RuntimeError(match["render_error"])
                except Exception as e:  # noqa: BLE001
                    msg = f"level {lvl} turn {t['turn']} action {t['action']}: transition()/render() raised {type(e).__name__}: {e}"
                    if msg not in errors and len(errors) < 8:
                        errors.append(msg)
                    if lvl_first is None:
                        lvl_first = {"level": lvl, "turn": t["turn"], "action": t["action"],
                                     "diff": f"{type(e).__name__}: {e}"}
            # Did the MODEL predict a change from prev? A transition is grading material if EITHER the
            # observed grid changed OR the model predicts a change — otherwise a model that invents a
            # change on a real no-op (e.g. "walks through a wall") slips through unscored and the
            # planner trusts a blocked move. (prev shape always == observed; pred shape may differ.)
            pred_changed = _predicts_change(pred, prev)
            if not obs_changed and not pred_changed:
                if pred is None:
                    n_unpredicted_noop += 1
                else:
                    n_joint_noop += 1
                continue
            if not obs_changed and pred_changed:
                n_false_change_on_noop += 1
            n_chg += 1
            strict_ok = bool(match and match.get("strict_ok"))
            ok = bool(match and match.get("accepted_ok"))
            cell_n += int(nxt.size)
            if pred is not None and pred.shape == nxt.shape:
                stats = (match or {}).get("primary_stats") or {}
                cell_ok += int(stats.get("full_cell_ok", np.count_nonzero(pred == nxt)))
                known_cell_ok += int(stats.get("known_cell_ok", 0))
                known_cell_n += int(stats.get("known_cell_n", 0))
                unknown_cell_n += int(stats.get("unknown_cell_n", 0))
                if int(stats.get("unknown_cell_n", 0)) > 0:
                    n_unknown_used += 1
            if ok:
                n_ok += 1
                if match.get("accepted_by_variant"):
                    n_variant_used += 1
                if match.get("accepted_by_unknown"):
                    n_unknown_accepts += 1
            if strict_ok:
                n_strict_ok += 1
            elif not ok and lvl_first is None:
                if pred is None:
                    lvl_first = {"level": lvl, "turn": t["turn"], "action": t["action"],
                                 "diff": "model produced no prediction (transition/render failed)"}
                elif pred.shape != nxt.shape:
                    lvl_first = {"level": lvl, "turn": t["turn"], "action": t["action"],
                                 "diff": f"render shape {pred.shape} != observed {nxt.shape} — render() must "
                                         f"return the full {nxt.shape} grid"}
                elif not obs_changed:
                    d = _known_mismatches(pred, nxt)
                    loc = tuple(int(v) for v in d[0]) if len(d) else "(no claimed cell)"
                    lvl_first = {"level": lvl, "turn": t["turn"], "action": t["action"],
                                 "diff": f"model changed {len(d)} cell(s) but the action was a real NO-OP "
                                         f"(observed grid unchanged); first at {loc}"}
                else:
                    best = (match or {}).get("best")
                    d = _known_mismatches(best if best is not None and best.shape == nxt.shape else pred, nxt)
                    loc = tuple(int(v) for v in d[0]) if len(d) else "(no claimed cell)"
                    vc = (match or {}).get("variant_count", 0)
                    variant_note = f"; {vc} observation variant(s) checked" if vc else ""
                    us = (match or {}).get("primary_stats") or {}
                    unknown_note = (f"; render() left {int(us.get('unknown_cell_n', 0))} cell(s) UNKNOWN"
                                    if int(us.get("unknown_cell_n", 0)) else "")
                    lvl_first = {"level": lvl, "turn": t["turn"], "action": t["action"],
                                 "diff": f"{len(d)} claimed cells differ; first at {loc}"
                                         f"{variant_note}{unknown_note}"}
        lvl_coverage = (known_cell_n / cell_n if cell_n else None)
        per[lvl] = {"simulation_accuracy": (n_ok / n_chg if n_chg else None),
                    "strict_simulation_accuracy": (n_strict_ok / n_chg if n_chg else None),
                    "cell_accuracy": (cell_ok / cell_n if cell_n else None),
                    "known_cell_accuracy": (known_cell_ok / known_cell_n if known_cell_n else None),
                    "prediction_coverage": lvl_coverage,
                    "prediction_coverage_status": _coverage_status(lvl_coverage),
                    "unknown_cell_rate": (unknown_cell_n / cell_n if cell_n else None),
                    "variant_acceptance_rate": (n_variant_used / n_chg if n_chg else None),
                    "variant_used": n_variant_used,
                    "unknown_acceptance_rate": (n_unknown_accepts / n_chg if n_chg else None),
                    "unknown_used": n_unknown_used,
                    "initial_render_ok": init_accepted,
                    "initial_render_strict_ok": init_strict,
                    "initial_render_accepted_label": ((initial_match or {}).get("accepted_label")),
                    "initial_render_cell_accuracy": (init_stats.get("full_cell_ok", 0) /
                                                     init_stats.get("cell_n", 1)
                                                     if init_stats.get("cell_n") else None),
                    "initial_render_known_cell_accuracy": init_stats.get("known_cell_accuracy"),
                    "initial_render_prediction_coverage": init_stats.get("coverage"),
                    "initial_render_coverage_status": init_stats.get("coverage_status", "unobserved"),
                    "initial_render_unknown_cell_rate": (init_stats.get("unknown_cell_n", 0) /
                                                         init_stats.get("cell_n", 1)
                                                         if init_stats.get("cell_n") else None),
                    "initial_render_variant_used": bool(initial_match and initial_match.get("accepted_by_variant")),
                    "initial_render_unknown_used": bool(init_stats.get("unknown_cell_n", 0)),
                    "initial_render_first_mismatch": init_first,
                    "initial_render_error": init_error,
                    "n_matched": n_ok,
                    "n_changing": n_chg,
                    "n_total": len(seq),
                    "n_observed_changed": n_observed_changed,
                    "n_observed_noop": n_observed_noop,
                    "n_joint_noop": n_joint_noop,
                    "n_unpredicted_noop": n_unpredicted_noop,
                    "n_false_change_on_noop": n_false_change_on_noop,
                    "first_divergence": lvl_first}
        total_chg += n_chg
        total_ok += n_ok
        total_strict_ok += n_strict_ok
        total_variant_used += n_variant_used
        total_cell_ok += cell_ok
        total_cell_n += cell_n
        total_known_cell_ok += known_cell_ok
        total_known_cell_n += known_cell_n
        total_unknown_cell_n += unknown_cell_n
        total_unknown_used += n_unknown_used
        total_unknown_accepts += n_unknown_accepts
        total_observed_changed += n_observed_changed
        total_observed_noop += n_observed_noop
        total_joint_noop += n_joint_noop
        total_unpredicted_noop += n_unpredicted_noop
        total_false_change_on_noop += n_false_change_on_noop

    first = next((per[l]["first_divergence"] for l in sorted(per) if per[l]["first_divergence"]), None)
    total_coverage = (total_known_cell_n / total_cell_n) if total_cell_n else None
    initial_coverage = (initial_known_cell_n / initial_cell_n) if initial_cell_n else None
    archived = attempts(root)
    archived_by_level = {}
    archived_transition_n = archived_changed_n = 0
    for attempt in archived:
        seq = transitions(attempt["root"])
        changed = sum(int(not np.array_equal(t["prev"], t["next"])) for t in seq)
        lvl = int(attempt.get("level", -1))
        rec = archived_by_level.setdefault(lvl, {
            "attempts": 0, "transitions": 0, "observed_changed": 0,
        })
        rec["attempts"] += 1
        rec["transitions"] += len(seq)
        rec["observed_changed"] += changed
        archived_transition_n += len(seq)
        archived_changed_n += changed
    return {
        "simulation_accuracy": (total_ok / total_chg) if total_chg else None,
        "strict_simulation_accuracy": (total_strict_ok / total_chg) if total_chg else None,
        "cell_accuracy": (total_cell_ok / total_cell_n) if total_cell_n else None,
        "known_cell_accuracy": (total_known_cell_ok / total_known_cell_n) if total_known_cell_n else None,
        "prediction_coverage": total_coverage,
        "prediction_coverage_status": _coverage_status(total_coverage),
        "unknown_cell_rate": (total_unknown_cell_n / total_cell_n) if total_cell_n else None,
        "variant_acceptance_rate": (total_variant_used / total_chg) if total_chg else None,
        "variant_used": total_variant_used,
        "unknown_acceptance_rate": (total_unknown_accepts / total_chg) if total_chg else None,
        "unknown_used": total_unknown_used,
        "initial_render_ok": (initial_ok == initial_n) if initial_n else None,
        "initial_render_accuracy": (initial_ok / initial_n) if initial_n else None,
        "initial_render_strict_accuracy": (initial_strict_ok / initial_n) if initial_n else None,
        "initial_render_cell_accuracy": (initial_cell_ok / initial_cell_n) if initial_cell_n else None,
        "initial_render_known_cell_accuracy": (initial_known_cell_ok / initial_known_cell_n)
                                              if initial_known_cell_n else None,
        "initial_render_prediction_coverage": initial_coverage,
        "initial_render_coverage_status": _coverage_status(initial_coverage),
        "initial_render_unknown_cell_rate": (initial_unknown_cell_n / initial_cell_n)
                                            if initial_cell_n else None,
        "initial_render_variant_used": initial_variant_used,
        "initial_render_unknown_used": initial_unknown_used,
        "n_initial_render": initial_n,
        "initial_render_errors": initial_render_errors,
        "variant_limit": OBSERVATION_VARIANT_LIMIT,
        "n_matched": total_ok,
        "n_changing": total_chg,
        "n_total": len(trans),
        "n_observed_changed": total_observed_changed,
        "n_observed_noop": total_observed_noop,
        "n_joint_noop": total_joint_noop,
        "n_unpredicted_noop": total_unpredicted_noop,
        "n_false_change_on_noop": total_false_change_on_noop,
        "archived_attempts": len(archived),
        "archived_transitions": archived_transition_n,
        "archived_observed_changed": archived_changed_n,
        "archived_by_level": archived_by_level,
        "ok": (total_chg > 0 and total_ok == total_chg),
        "per_level": per,
        "first_divergence": first,
        "errors": errors,
        "variant_errors": variant_errors,
    }


def death_events(root="."):
    """Fatal/reset evidence recorded outside normal transitions.

    Each event is a non-RESET action whose result was GAME_OVER. The following RESET starts a fresh
    level attempt, so these are not ordinary dynamics transitions; they are negative constraints the
    model/planner should account for.
    """
    out = []
    for f in glob.glob(os.path.join(root, "level_*", "death_*.json")):
        if f.endswith(("_prev.json", "_next.json")):
            continue
        try:
            event = json.load(open(f))
            out.append(event)
        except Exception:  # noqa: BLE001
            pass
    return sorted(out, key=lambda e: (int(e.get("level", -1)), int(e.get("turn", -1))))


def animation_index(root=".", *, level=None, turn=None, last=None, details=False):
    """Compact metadata for transient animation evidence.

    Animation frames are not playable decision states and do not enter frames() or
    transitions(). Use this index first to find events; call animation_grids(...) only
    for one event when you need numeric frame arrays.

    Filter with level=, turn=, or last=N before loading an event. The compact default omits path
    lists and classifier feature vectors; details=True includes them. Returns metadata only,
    sorted by (level, turn, directory). No grids are loaded.
    """
    out = []
    pattern = os.path.join(root, "level_*", "animation_*", "meta.json")
    for f in glob.glob(pattern):
        try:
            ev = json.load(open(f))
            decision = ev.get("decision") or {}
            all_files = ev.get("all_frame_files") or ev.get("selected_frame_files", [])
            selected_files = ev.get("selected_frame_files", [])
            item = {
                "level": ev.get("level"),
                "turn": ev.get("turn"),
                "action": ev.get("action"),
                "row": ev.get("row"),
                "col": ev.get("col"),
                "terminal": ev.get("terminal", "nonterminal"),
                "directory": ev.get("directory"),
                "original_frame_count": ev.get("original_frame_count"),
                "selected_frame_indices": ev.get("selected_frame_indices", []),
                "category": decision.get("category"),
                "surface": decision.get("surface"),
                "reasons": decision.get("reasons", []),
                "summary": ev.get("summary", ""),
                "summary_reused": bool(ev.get("summary_reused", False)),
                "summary_skipped": ev.get("summary_skipped", ""),
            }
            if details:
                item.update({
                    "features": decision.get("features", {}),
                    "frame_paths": [entry.get("txt") for entry in all_files if entry.get("txt")],
                    "keyframe_paths": [entry.get("txt") for entry in selected_files if entry.get("txt")],
                    "png_paths": [entry.get("png") for entry in all_files if entry.get("png")],
                    "keyframe_png_paths": [entry.get("png") for entry in selected_files if entry.get("png")],
                })
            out.append(item)
        except Exception:  # noqa: BLE001
            pass
    out = sorted(out, key=lambda e: (
        int(e.get("level", -1)),
        int(e.get("turn", -1)),
        str(e.get("directory", "")),
    ))
    if level is not None:
        out = [e for e in out if int(e.get("level", -1)) == int(level)]
    if turn is not None:
        out = [e for e in out if int(e.get("turn", -1)) == int(turn)]
    if last is not None:
        last = int(last)
        if last < 0:
            raise ValueError("animation_index(last=N) requires N >= 0")
        out = out[-last:] if last else []
    return out


def _animation_meta(root, event_or_dir):
    if isinstance(event_or_dir, dict):
        directory = event_or_dir.get("directory")
    else:
        directory = str(event_or_dir)
    if not directory:
        raise ValueError("animation_grids needs an event dict from animation_index() or an event directory")
    meta_path = os.path.join(root, directory, "meta.json")
    if not os.path.exists(meta_path):
        raise FileNotFoundError(f"animation event not found or pruned: {directory}")
    return json.load(open(meta_path))


def animation_grids(event_or_dir, *, root=".", keyframes=False, indices=None):
    """Load numeric grids for one saved animation event.

    event_or_dir may be an event dict returned by animation_index() or a directory string
    like "level_5/animation_066_ACTION5". By default this returns every retained frame
    for that one event. Use keyframes=True for only summary-selected keyframes, or
    indices=[...] to load specific original frame indices.
    """
    ev = _animation_meta(root, event_or_dir)
    if keyframes and indices is not None:
        raise ValueError("pass either keyframes=True or indices=[...], not both")
    if keyframes:
        items = ev.get("selected_frame_files", [])
    else:
        items = ev.get("all_frame_files") or ev.get("selected_frame_files", [])
    if indices is not None:
        wanted = {int(i) for i in indices}
        items = [item for item in items if int(item.get("index", -1)) in wanted]
        found = {int(item.get("index", -1)) for item in items}
        missing = sorted(wanted - found)
        if missing:
            raise ValueError(f"animation frame indices not found: {missing}")
    grids = []
    for item in items:
        rel = item.get("txt")
        if not rel:
            continue
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            raise FileNotFoundError(f"animation frame not found or pruned: {rel}")
        grids.append(_read(path))
    return grids


# ---- outcome verification (necessary-not-sufficient: perfect dynamics with wrong outcome scores poorly) ----
def solved_actions(root="."):
    """{level: {action,row,col}} — the action that COMPLETED each level, written by the harness
    (level_<L>/solved.json) the moment a level finished. When available, terminal_events() holds the
    observed winning frame; solved.json remains the fallback action record for older workspaces."""
    out = {}
    for f in glob.glob(os.path.join(root, "level_*", "solved.json")):
        lvl = int(os.path.basename(os.path.dirname(f)).split("_")[1])
        try:
            out[lvl] = json.load(open(f))
        except Exception:  # noqa: BLE001
            pass
    return out


def terminal_events(root="."):
    """{level: {pre_turn, action:{action,row,col}, terminal_grid (np int16), outcome}} — the OBSERVED
    winning terminal per solved level, recorded by the harness (level_<L>/terminal.json) as a SEPARATE
    channel (NOT a turn_*.txt decision frame). terminal_grid is the first frame the winning action
    produced — the goal-reached state of that level, before the engine advanced. This is the render
    ground-truth verify_outcome bridges to: the modeled post-win state must have
    outcome(state) == "level_complete" AND render to this grid. The agent never acts from it,
    so it is excluded from frames()/transitions()."""
    out = {}
    for f in glob.glob(os.path.join(root, "level_*", "terminal.json")):
        try:
            ev = json.load(open(f))
            ev["terminal_grid"] = np.asarray(ev["terminal_grid"], dtype=np.int16)
            out[int(ev["level"])] = ev
        except Exception:  # noqa: BLE001
            pass
    return out


def _safe_outcome(model, state, errors, context, level_errors=None):
    if state is None:
        return None
    try:
        return outcome(model, state)
    except Exception as e:  # noqa: BLE001
        msg = f"{context}: outcome() raised {type(e).__name__}: {e}"
        if msg not in errors and len(errors) < 8:
            errors.append(msg)
        if level_errors is not None and msg not in level_errors and len(level_errors) < 8:
            level_errors.append(msg)
        return None


def verify_outcome(model, root="."):
    """Falsify outcome() against observed level-complete and GAME_OVER evidence.

    For each solved level L:
      1. Replay from init_state(L's first frame, L) through L's observed transitions to the PRE-WIN
         state s_pre (the state the winning action was taken from).
      2. Apply the recorded winning action once: s_terminal = transition(s_pre, winning_action).
      3. Grade the terminal: outcome(s_terminal) must be "level_complete"; AND, when the observed
         terminal grid is available, render(s_terminal) must equal it (the render bridge).
      4. Grade every OBSERVED decision state: outcome(state) must be "ongoing".
    For each API GAME_OVER event, replay the recorded failed-attempt prefix when available, then apply
    the fatal action and require outcome(s_next) == "game_over". The prefix matters when hidden state
    is accumulated in State rather than re-read from the pre-fatal grid. Reset-like NOT_FINISHED
    transitions are ordinary dynamics, not loss terminals.

    Returns outcome rates plus terminal render diagnostics. Misfires include:
      ("missed-level-complete"|"false-level-complete"|"missed-game-over"|"false-game-over"|
       "terminal-render", level, turn).
    """
    fr = frames(root)
    by_level = {}
    for (lvl, t), g in fr.items():
        by_level.setdefault(lvl, {})[t] = g
    levels = sorted(by_level)
    won = solved_actions(root)
    term_ev = terminal_events(root)
    trans_by_level = {}
    for t in transitions(root):
        trans_by_level.setdefault(t["level"], []).append(t)

    def _bucket():
        return {
            "level_hits": 0, "level_n": 0,
            "game_over_hits": 0, "game_over_n": 0,
            "false_level": 0, "false_game_over": 0, "nonterm_n": 0,
            "render_exact": 0, "render_strict_exact": 0, "render_variant_used": 0,
            "render_cell_ok": 0, "render_cell_n": 0,
            "render_known_cell_ok": 0, "render_known_cell_n": 0, "render_unknown_cell_n": 0,
            "render_unknown_used": 0, "render_unknown_accepts": 0, "render_n": 0,
            "outcome_errors": [], "misfires": [],
        }

    per_counts = {}

    def _level_bucket(lvl):
        return per_counts.setdefault(int(lvl), _bucket())

    def _add_error(lvl, msg):
        if msg not in outcome_errors and len(outcome_errors) < 8:
            outcome_errors.append(msg)
        lb = _level_bucket(lvl)
        if msg not in lb["outcome_errors"] and len(lb["outcome_errors"]) < 8:
            lb["outcome_errors"].append(msg)

    def _add_misfire(kind, lvl, turn):
        item = (kind, int(lvl), int(turn))
        if len(misfires) < 12:
            misfires.append(item)
        lb = _level_bucket(lvl)
        if len(lb["misfires"]) < 12:
            lb["misfires"].append(item)

    def _finish_bucket(b):
        level_complete_ok = ((b["level_n"] == 0 or b["level_hits"] == b["level_n"])
                             and b["false_level"] == 0)
        game_over_ok = ((b["game_over_n"] == 0 or b["game_over_hits"] == b["game_over_n"])
                        and b["false_game_over"] == 0)
        terminal_coverage = (b["render_known_cell_n"] / b["render_cell_n"]) if b["render_cell_n"] else None
        terminal_render_ok = (b["render_exact"] == b["render_n"]) if b["render_n"] else None
        outcome_ok = level_complete_ok and game_over_ok and not b["outcome_errors"]
        return {
            "level_complete_on_terminal": (b["level_hits"] / b["level_n"]) if b["level_n"] else None,
            "level_complete_on_nonterminal": (b["false_level"] / b["nonterm_n"]) if b["nonterm_n"] else None,
            "game_over_on_death": (b["game_over_hits"] / b["game_over_n"]) if b["game_over_n"] else None,
            "game_over_on_nonterminal": (b["false_game_over"] / b["nonterm_n"]) if b["nonterm_n"] else None,
            "outcome_ok": outcome_ok,
            "level_complete_ok": level_complete_ok,
            "game_over_ok": game_over_ok,
            "terminal_render_ok": terminal_render_ok,
            "ok": (outcome_ok and (terminal_render_ok is not False)),
            "n_level_complete_terminal": b["level_n"],
            "n_game_over_terminal": b["game_over_n"],
            "n_nonterminal": b["nonterm_n"],
            "terminal_render_exact": (b["render_exact"] / b["render_n"]) if b["render_n"] else None,
            "terminal_render_strict_exact": (
                b["render_strict_exact"] / b["render_n"] if b["render_n"] else None
            ),
            "terminal_render_cell": (
                b["render_cell_ok"] / b["render_cell_n"] if b["render_cell_n"] else None
            ),
            "terminal_render_known_cell": (
                b["render_known_cell_ok"] / b["render_known_cell_n"] if b["render_known_cell_n"] else None
            ),
            "terminal_render_prediction_coverage": terminal_coverage,
            "terminal_render_coverage_status": _coverage_status(terminal_coverage),
            "terminal_render_unknown_cell_rate": (
                b["render_unknown_cell_n"] / b["render_cell_n"] if b["render_cell_n"] else None
            ),
            "terminal_render_variant_acceptance_rate": (
                b["render_variant_used"] / b["render_n"] if b["render_n"] else None
            ),
            "terminal_render_variant_used": b["render_variant_used"],
            "terminal_render_unknown_acceptance_rate": (
                b["render_unknown_accepts"] / b["render_n"] if b["render_n"] else None
            ),
            "terminal_render_unknown_used": b["render_unknown_used"],
            "outcome_errors": list(b["outcome_errors"]),
            "level_complete_observable": b["level_n"] > 0,
            "game_over_observable": b["game_over_n"] > 0,
            "outcome_observable": b["level_n"] > 0 or b["game_over_n"] > 0,
            "misfires": list(b["misfires"]),
        }

    level_hits = level_n = 0
    game_over_hits = game_over_n = 0
    false_level = false_game_over = nonterm_n = 0
    render_exact = render_strict_exact = render_variant_used = render_cell_ok = render_cell_n = render_n = 0
    render_known_cell_ok = render_known_cell_n = render_unknown_cell_n = 0
    render_unknown_used = render_unknown_accepts = 0
    variant_errors = []
    outcome_errors = []
    misfires = []
    for lvl in levels:
        lb = _level_bucket(lvl)
        turns = sorted(by_level[lvl])
        seq = trans_by_level.get(lvl, [])
        try:
            state = model.init_state(by_level[lvl][turns[0]], lvl)
        except Exception:  # noqa: BLE001
            state = None
        # (4) every OBSERVED decision state is non-terminal. Thread to s_pre.
        for i, t in enumerate(turns):
            out = _safe_outcome(
                model, state, outcome_errors, f"level {lvl} turn {t}", lb["outcome_errors"]
            )
            if out == OUTCOME_LEVEL_COMPLETE:
                false_level += 1
                lb["false_level"] += 1
                _add_misfire("false-level-complete", lvl, t)
            elif out == OUTCOME_GAME_OVER:
                false_game_over += 1
                lb["false_game_over"] += 1
                _add_misfire("false-game-over", lvl, t)
            nonterm_n += 1
            lb["nonterm_n"] += 1
            if state is not None and i < len(seq):
                try:
                    state = model.transition(state, _act(seq[i]))
                except Exception:  # noqa: BLE001
                    state = None
        # (1-3) terminal: apply the winning action to s_pre, then grade outcome() + the render bridge.
        ev = term_ev.get(lvl)
        win = (ev["action"] if ev else won.get(lvl))
        if win is not None:
            level_n += 1
            lb["level_n"] += 1
            s_term = None
            if state is not None:
                try:
                    s_term = model.transition(state, {"action": win.get("action"),
                                                      "row": win.get("row"), "col": win.get("col")})
                except Exception:  # noqa: BLE001
                    s_term = None
            out = _safe_outcome(
                model, s_term, outcome_errors, f"level {lvl} terminal", lb["outcome_errors"]
            )
            if out == OUTCOME_LEVEL_COMPLETE:
                level_hits += 1
                lb["level_hits"] += 1
            else:
                _add_misfire("missed-level-complete", lvl, turns[-1])
            # render bridge: model's terminal must render to the OBSERVED winning grid (when recorded).
            if ev is not None:
                render_n += 1
                lb["render_n"] += 1
                obs = ev["terminal_grid"]
                match = None
                pred = None
                if s_term is not None:
                    try:
                        match = _render_match(model, s_term, obs)
                        pred = match["primary"]
                        for ve in match.get("variant_errors") or []:
                            msg = f"level {lvl} terminal: {ve}"
                            if msg not in variant_errors and len(variant_errors) < 8:
                                variant_errors.append(msg)
                        if match.get("variant_truncated"):
                            msg = (f"level {lvl} terminal: observation_variants() returned more than "
                                   f"{OBSERVATION_VARIANT_LIMIT}; extras ignored")
                            if msg not in variant_errors and len(variant_errors) < 8:
                                variant_errors.append(msg)
                    except Exception:  # noqa: BLE001
                        pred = None
                if pred is not None and pred.shape == obs.shape:
                    stats = (match or {}).get("primary_stats") or {}
                    render_cell_n += int(obs.size)
                    lb["render_cell_n"] += int(obs.size)
                    full_ok = int(stats.get("full_cell_ok", np.count_nonzero(pred == obs)))
                    known_ok = int(stats.get("known_cell_ok", 0))
                    known_n = int(stats.get("known_cell_n", 0))
                    unknown_n = int(stats.get("unknown_cell_n", 0))
                    render_cell_ok += full_ok
                    lb["render_cell_ok"] += full_ok
                    render_known_cell_ok += known_ok
                    lb["render_known_cell_ok"] += known_ok
                    render_known_cell_n += known_n
                    lb["render_known_cell_n"] += known_n
                    render_unknown_cell_n += unknown_n
                    lb["render_unknown_cell_n"] += unknown_n
                    if unknown_n > 0:
                        render_unknown_used += 1
                        lb["render_unknown_used"] += 1
                    if match and match.get("strict_ok"):
                        render_strict_exact += 1
                        lb["render_strict_exact"] += 1
                    if match and match.get("accepted_ok"):
                        render_exact += 1
                        lb["render_exact"] += 1
                        if match.get("accepted_by_variant"):
                            render_variant_used += 1
                            lb["render_variant_used"] += 1
                        if match.get("accepted_by_unknown"):
                            render_unknown_accepts += 1
                            lb["render_unknown_accepts"] += 1
                    else:
                        _add_misfire("terminal-render", lvl, ev.get("pre_turn", turns[-1]))
                else:
                    _add_misfire("terminal-render", lvl, ev.get("pre_turn", turns[-1]))

    for ev in death_events(root):
        game_over_n += 1
        lvl = int(ev.get("level", -1))
        lb = _level_bucket(lvl)
        lb["game_over_n"] += 1
        turn = int(ev.get("turn", -1))
        prev = ev.get("prev")
        attempt_start = ev.get("attempt_start")
        attempt_actions = ev.get("attempt_actions") or []
        state = None
        s_term = None
        if attempt_start is not None:
            try:
                state = model.init_state(np.asarray(attempt_start, dtype=np.int16), lvl)
                for a in attempt_actions:
                    state = model.transition(state, {"action": a.get("action"),
                                                     "row": a.get("row"), "col": a.get("col")})
                s_term = model.transition(state, {"action": ev.get("action"),
                                                  "row": ev.get("row"), "col": ev.get("col")})
            except Exception as e:  # noqa: BLE001
                _add_error(lvl, f"level {lvl} death {turn}: transition() raised {type(e).__name__}: {e}")
        elif prev is not None:
            try:
                state = model.init_state(np.asarray(prev, dtype=np.int16), lvl)
                s_term = model.transition(state, {"action": ev.get("action"),
                                                  "row": ev.get("row"), "col": ev.get("col")})
            except Exception as e:  # noqa: BLE001
                _add_error(lvl, f"level {lvl} death {turn}: transition() raised {type(e).__name__}: {e}")
        out = _safe_outcome(
            model, s_term, outcome_errors, f"level {lvl} death {turn}", lb["outcome_errors"]
        )
        if out == OUTCOME_GAME_OVER:
            game_over_hits += 1
            lb["game_over_hits"] += 1
        else:
            _add_misfire("missed-game-over", lvl, turn)

    level_complete_ok = ((level_n == 0 or level_hits == level_n) and false_level == 0)
    game_over_ok = ((game_over_n == 0 or game_over_hits == game_over_n) and false_game_over == 0)
    terminal_coverage = (render_known_cell_n / render_cell_n) if render_cell_n else None
    terminal_render_ok = (render_exact == render_n) if render_n else None
    outcome_ok = level_complete_ok and game_over_ok and not outcome_errors
    per_level = {lvl: _finish_bucket(b) for lvl, b in sorted(per_counts.items())}
    return {"level_complete_on_terminal": (level_hits / level_n) if level_n else None,
            "level_complete_on_nonterminal": (false_level / nonterm_n) if nonterm_n else None,
            "game_over_on_death": (game_over_hits / game_over_n) if game_over_n else None,
            "game_over_on_nonterminal": (false_game_over / nonterm_n) if nonterm_n else None,
            "outcome_ok": outcome_ok,
            "level_complete_ok": level_complete_ok,
            "game_over_ok": game_over_ok,
            "terminal_render_ok": terminal_render_ok,
            "ok": (outcome_ok and (terminal_render_ok is not False)),
            "n_level_complete_terminal": level_n,
            "n_game_over_terminal": game_over_n,
            "n_nonterminal": nonterm_n,
            "terminal_render_exact": (render_exact / render_n) if render_n else None,
            "terminal_render_strict_exact": (render_strict_exact / render_n) if render_n else None,
            "terminal_render_cell": (render_cell_ok / render_cell_n) if render_cell_n else None,
            "terminal_render_known_cell": (render_known_cell_ok / render_known_cell_n) if render_known_cell_n else None,
            "terminal_render_prediction_coverage": terminal_coverage,
            "terminal_render_coverage_status": _coverage_status(terminal_coverage),
            "terminal_render_unknown_cell_rate": (render_unknown_cell_n / render_cell_n) if render_cell_n else None,
            "terminal_render_variant_acceptance_rate": (render_variant_used / render_n) if render_n else None,
            "terminal_render_variant_used": render_variant_used,
            "terminal_render_unknown_acceptance_rate": (render_unknown_accepts / render_n) if render_n else None,
            "terminal_render_unknown_used": render_unknown_used,
            "variant_errors": variant_errors,
            "outcome_errors": outcome_errors,
            "level_complete_observable": level_n > 0,
            "game_over_observable": game_over_n > 0,
            "outcome_observable": level_n > 0 or game_over_n > 0,
            "misfires": misfires,
            "per_level": per_level}


# ---- planners (search over State via your transition/outcome) ----
def _planner_key(model, state):
    """Return a search key, using an optional exact semantic projection.

    Pixel-heavy models often keep immutable terrain or render caches in ``State``. Hashing those
    fields at every node is correct but needlessly expensive. A model may therefore define
    ``planner_key(state)`` returning only fields that distinguish future dynamics and outcomes.
    The generic full-state key remains the default.
    """
    hook = getattr(model, "planner_key", None)
    value = hook(state) if callable(hook) else state
    return _hashable(value)


def _planner_successor(model, state, action):
    """Apply one planner edge without copying twice when the model promises a fresh result.

    Historical models were allowed to mutate their input, so the safe default still clones.
    New seeded models declare ``TRANSITION_RETURNS_NEW_STATE = True`` and clone internally.
    """
    source = state if getattr(model, "TRANSITION_RETURNS_NEW_STATE", False) else clone(state)
    return model.transition(source, action)


def _acts(model, state):
    try:
        raw_actions = list(model.actions(state))
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(f"actions(state) raised {type(e).__name__}: {e}") from e
    if raw_actions:
        return [_norm_action(a, strict=True) for a in raw_actions]
    return [{"action": x, "row": None, "col": None} for x in ("ACTION1", "ACTION2", "ACTION3", "ACTION4")]


def _norm_action(a, *, strict=False):
    if isinstance(a, dict):
        if strict and "action" not in a:
            raise ValueError(
                "actions(state) must return dicts with an 'action' key; "
                f"got {a!r}"
            )
        return {"action": a.get("action"), "row": a.get("row"), "col": a.get("col")}
    if strict:
        raise ValueError(
            "actions(state) must return full action dicts "
            '{"action": "...", "row": None, "col": None}; '
            f"got {type(a).__name__} {a!r}"
        )
    return {"action": a, "row": None, "col": None}


def _click_regions(cells, limit=GAME_OVER_CLICK_REGION_LIMIT):
    """Compact row/col-run rectangles for ACTION6 cells."""
    if not cells:
        return []
    by_row = {}
    for r, c in sorted(set(cells)):
        by_row.setdefault(int(r), []).append(int(c))
    rowspec = [(r, _runs(cols)) for r, cols in sorted(by_row.items())]
    out = []
    i = 0
    while i < len(rowspec) and len(out) < limit:
        r0, spec = rowspec[i]
        j = i
        while j + 1 < len(rowspec) and rowspec[j + 1][1] == spec and rowspec[j + 1][0] == rowspec[j][0] + 1:
            j += 1
        rr = f"rows {r0}-{rowspec[j][0]}" if j > i else f"row {r0}"
        out.append(f"{rr}, cols {spec}")
        i = j + 1
    if i < len(rowspec):
        out.append(f"... +{len(rowspec) - i} more row group(s)")
    return out


def game_over_action_report(model, state=None, root=".", max_actions=GAME_OVER_ACTION_SCAN_LIMIT):
    """Model-predicted one-step GAME_OVER actions from `state`.

    This is diagnostic feedback for the agent. It uses only the agent-authored model's actions(),
    transition(), and outcome(); it does not infer hazards from pixels or from the harness. ACTION6
    cells are grouped into compact row/col regions by format_game_over_action_report().
    """
    if state is None:
        state = current_state(model, root)
    if state is None:
        return {"checked": 0, "fatal": 0, "actions": [], "click_cells": [], "errors": ["no current state"]}
    try:
        acts = list(model.actions(state))
    except Exception as e:  # noqa: BLE001
        return {"checked": 0, "fatal": 0, "actions": [], "click_cells": [],
                "errors": [f"actions() raised {type(e).__name__}: {e}"]}
    checked = fatal = 0
    fatal_actions = []
    click_cells = []
    errors = []
    truncated = False
    for i, raw in enumerate(acts):
        if i >= max_actions:
            truncated = True
            break
        try:
            act = _norm_action(raw, strict=True)
        except Exception as e:  # noqa: BLE001
            if len(errors) < 3:
                errors.append(f"actions() item {i}: {type(e).__name__}: {e}")
            continue
        checked += 1
        try:
            nxt = _planner_successor(model, state, act)
            if is_game_over(model, nxt):
                fatal += 1
                if act.get("action") == "ACTION6" and act.get("row") is not None and act.get("col") is not None:
                    click_cells.append((int(act["row"]), int(act["col"])))
                elif len(fatal_actions) < GAME_OVER_ACTION_EXAMPLE_LIMIT:
                    fatal_actions.append(act)
        except Exception as e:  # noqa: BLE001
            if len(errors) < 3:
                errors.append(f"{act}: {type(e).__name__}: {e}")
    return {"checked": checked, "fatal": fatal, "actions": fatal_actions, "click_cells": click_cells,
            "truncated": truncated, "errors": errors}


def format_game_over_action_report(report):
    """One compact line for verifier feedback."""
    if report.get("errors") and not report.get("checked"):
        return f"MODEL_GAME_OVER_ACTIONS: check skipped ({'; '.join(report['errors'][:2])})"
    checked = int(report.get("checked") or 0)
    fatal = int(report.get("fatal") or 0)
    if fatal == 0:
        suffix = " (scan truncated)" if report.get("truncated") else ""
        if report.get("errors"):
            suffix += " errors: " + "; ".join(report["errors"][:2])
        return f"MODEL_GAME_OVER_ACTIONS: none among {checked} model candidate action(s) from current_state{suffix}."
    bits = []
    acts = report.get("actions") or []
    if acts:
        bits.append("non-click " + ", ".join(
            f"{a.get('action')}" + (f"({a.get('row')},{a.get('col')})" if a.get("row") is not None else "")
            for a in acts
        ))
    clicks = report.get("click_cells") or []
    if clicks:
        bits.append(f"ACTION6 {len(clicks)} cell(s): " + "; ".join(_click_regions(clicks)))
    if report.get("truncated"):
        bits.append("scan truncated")
    if report.get("errors"):
        bits.append("errors: " + "; ".join(report["errors"][:2]))
    return (f"MODEL_GAME_OVER_ACTIONS: model predicts {fatal}/{checked} candidate action(s) from "
            f"current_state lead to game_over — " + " | ".join(bits))


def _target(model, target):
    return target or (lambda s: is_level_complete(model, s))


def _is_target(target, state):
    try:
        return bool(target(state))
    except Exception:  # noqa: BLE001
        return False


def _should_prune(model, state):
    try:
        return is_game_over(model, state)
    except Exception:  # noqa: BLE001
        return False


def plan_bfs_with_diagnostics(model, start, target=None, max_nodes=20000, prune_game_over=True):
    """BFS with explicit no-plan diagnostics.

    status is:
      found                 plan reached target
      no_plan_exhausted     reachable state graph was exhausted within max_nodes
      no_plan_within_budget max_nodes stopped search while a frontier remained
    """
    target = _target(model, target)
    q = deque([(start, [])]); seen = {_planner_key(model, start)}; n = 0; errors = []
    while q and n < max_nodes:
        st, path = q.popleft(); n += 1
        if _is_target(target, st):
            return {"status": "found", "plan": path, "expanded_nodes": n,
                    "frontier_remaining": bool(q), "seen_states": len(seen), "errors": errors}
        if prune_game_over and _should_prune(model, st):
            continue
        try:
            actions = _acts(model, st)
        except Exception as e:  # noqa: BLE001
            return {"status": "actions_error", "plan": None, "expanded_nodes": n,
                    "frontier_remaining": bool(q), "seen_states": len(seen),
                    "errors": [f"{type(e).__name__}: {e}"]}
        for a in actions:
            try:
                nx = _planner_successor(model, st, a)
            except Exception as e:  # noqa: BLE001
                if len(errors) < 5:
                    errors.append(f"transition({a}) raised {type(e).__name__}: {e}")
                continue
            k = _planner_key(model, nx)
            if k not in seen:
                seen.add(k); q.append((nx, path + [a]))
    status = "no_plan_within_budget" if q else "no_plan_exhausted"
    return {"status": status, "plan": None, "expanded_nodes": n,
            "frontier_remaining": bool(q), "seen_states": len(seen), "errors": errors}


def plan_bfs(model, start, target=None, max_nodes=20000, prune_game_over=True):
    """Shortest action sequence from `start` to a target state. By default the target is
    outcome(state) == "level_complete", and states with outcome(state) == "game_over" are pruned.
    Returns the action list, or None if unreachable within max_nodes."""
    diag = plan_bfs_with_diagnostics(model, start, target, max_nodes, prune_game_over)
    return diag.get("plan") if diag.get("status") == "found" else None


def plan_astar_with_diagnostics(model, start, target=None, heuristic=None,
                                max_nodes=20000, prune_game_over=True):
    """A* with explicit no-plan diagnostics.

    status is:
      found                 plan reached target
      no_plan_exhausted     reachable state graph was exhausted within max_nodes
      no_plan_within_budget max_nodes stopped search while a frontier remained
    """
    target = _target(model, target)
    h = heuristic or (lambda _s: 0); cnt = 0
    pq = [(h(start), 0, cnt, start, [])]
    best = {_planner_key(model, start): 0}; n = 0; errors = []
    while pq and n < max_nodes:
        _, g, _, st, path = heapq.heappop(pq)
        if best.get(_planner_key(model, st)) != g:
            continue
        n += 1
        if _is_target(target, st):
            return {"status": "found", "plan": path, "expanded_nodes": n,
                    "frontier_remaining": bool(pq), "seen_states": len(best), "errors": errors}
        if prune_game_over and _should_prune(model, st):
            continue
        try:
            actions = _acts(model, st)
        except Exception as e:  # noqa: BLE001
            return {"status": "actions_error", "plan": None, "expanded_nodes": n,
                    "frontier_remaining": bool(pq), "seen_states": len(best),
                    "errors": [f"{type(e).__name__}: {e}"]}
        for a in actions:
            try:
                nx = _planner_successor(model, st, a)
            except Exception as e:  # noqa: BLE001
                if len(errors) < 5:
                    errors.append(f"transition({a}) raised {type(e).__name__}: {e}")
                continue
            ng = g + 1; k = _planner_key(model, nx)
            if k in best and best[k] <= ng:
                continue
            best[k] = ng; cnt += 1
            heapq.heappush(pq, (ng + h(nx), ng, cnt, nx, path + [a]))
    status = "no_plan_within_budget" if pq else "no_plan_exhausted"
    return {"status": status, "plan": None, "expanded_nodes": n,
            "frontier_remaining": bool(pq), "seen_states": len(best), "errors": errors}


def plan_astar(model, start, target=None, heuristic=None, max_nodes=20000, prune_game_over=True):
    """A* from `start` to a target state, guided by heuristic(state)->estimated moves (default 0 =
    uninformed = BFS). By default the target is outcome(state) == "level_complete", and
    outcome(state) == "game_over" states are pruned."""
    diag = plan_astar_with_diagnostics(model, start, target, heuristic, max_nodes, prune_game_over)
    return diag.get("plan") if diag.get("status") == "found" else None


def validate_plan(model, start, plan, target=None, capture_renders=False):
    """Replay a candidate action sequence through the canonical executable model.

    Compact/custom search is only an acceleration mechanism: a plan is accepted when every
    canonical transition succeeds and the final canonical state satisfies ``target`` (by default,
    ``outcome(state) == "level_complete"``). Optional captured renders support guarded replay
    artifacts without changing the validation criterion.
    """
    target = _target(model, target)
    state = clone(start)
    actions = []
    renders = []
    errors = []
    for index, raw in enumerate(plan or []):
        try:
            action = _norm_action(raw, strict=True)
        except Exception as e:  # noqa: BLE001
            return {
                "status": "invalid_action",
                "plan": None,
                "steps_validated": index,
                "final_outcome": None,
                "errors": [f"action {index + 1}: {type(e).__name__}: {e}"],
                "renders": renders,
            }
        try:
            state = _planner_successor(model, state, action)
            if capture_renders:
                renders.append(np.asarray(model.render(state), dtype=np.int16).copy())
        except Exception as e:  # noqa: BLE001
            return {
                "status": "transition_error",
                "plan": None,
                "steps_validated": index,
                "final_outcome": None,
                "errors": [f"step {index + 1} {action}: {type(e).__name__}: {e}"],
                "renders": renders,
            }
        actions.append(action)
    try:
        final_outcome = outcome(model, state)
        reached = _is_target(target, state)
    except Exception as e:  # noqa: BLE001
        final_outcome = None
        reached = False
        errors.append(f"final target/outcome: {type(e).__name__}: {e}")
    return {
        "status": "found" if reached else "goal_not_reached",
        "plan": actions if reached else None,
        "steps_validated": len(actions),
        "final_outcome": final_outcome,
        "errors": errors,
        "renders": renders,
    }


def _subgoal_label(goal, index):
    name = getattr(goal, "__name__", None)
    if name and name != "<lambda>":
        return name
    return f"subgoal_{index + 1}"


def plan_subgoals_with_diagnostics(model, start, subgoals, heuristic=None, max_nodes=20000):
    """Plan through ordered target-style callables and report per-leg diagnostics.

    Returns a dict with:
      status: "found" or "failed_at_subgoal"
      plan: concatenated action list on success, else None
      subgoal_count, subgoal_labels, leg_lengths
      failed_index/failed_ordinal/failed_label/completed_prefix_len on failure

    This is the diagnostic form used by auto-feedback and plan.py. plan_subgoals() below keeps the
    historical simple API for agent-authored code that expects only list-or-None.
    """
    goals = list(subgoals or [])
    st = start
    full = []
    labels = [_subgoal_label(gt, i) for i, gt in enumerate(goals)]
    leg_lengths = []
    for i, gt in enumerate(goals):
        leg_diag = plan_astar_with_diagnostics(model, st, gt, heuristic, max_nodes)
        leg = leg_diag.get("plan") if leg_diag.get("status") == "found" else None
        if leg is None:
            return {
                "status": "failed_at_subgoal",
                "plan": None,
                "subgoal_count": len(goals),
                "subgoal_labels": labels,
                "leg_lengths": leg_lengths,
                "failed_index": i,
                "failed_ordinal": i + 1,
                "failed_label": labels[i],
                "completed_prefix_len": len(full),
                "failed_reason": leg_diag.get("status", "no_plan_within_budget"),
                "failed_expanded_nodes": leg_diag.get("expanded_nodes"),
                "failed_frontier_remaining": leg_diag.get("frontier_remaining"),
                "failed_errors": leg_diag.get("errors") or [],
            }
        try:
            for a in leg:
                st = model.transition(st, a)
        except Exception as e:  # noqa: BLE001
            return {
                "status": "failed_at_subgoal",
                "plan": None,
                "subgoal_count": len(goals),
                "subgoal_labels": labels,
                "leg_lengths": leg_lengths,
                "failed_index": i,
                "failed_ordinal": i + 1,
                "failed_label": labels[i],
                "completed_prefix_len": len(full),
                "failed_reason": f"transition_error:{type(e).__name__}: {e}",
            }
        full += leg
        leg_lengths.append(len(leg))
    return {
        "status": "found",
        "plan": full,
        "subgoal_count": len(goals),
        "subgoal_labels": labels,
        "leg_lengths": leg_lengths,
        "completed_prefix_len": len(full),
    }


def plan_subgoals(model, start, subgoals, heuristic=None, max_nodes=20000):
    """Plan through an ordered list of target-style callables. Returns the concatenated plan or None."""
    diag = plan_subgoals_with_diagnostics(model, start, subgoals, heuristic, max_nodes)
    return diag.get("plan") if diag.get("status") == "found" else None
